Fix proposal for #285
picklepete/pyicloud pull request #300
Opened 2020-09-18 20:01 UTC by jfburdet

## Proposed change

Some albums can have null names, which make the current code bash crashing. This changes avoid crash by skipping those kind of albums

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New service (thank you!)
- [ ] New feature (which adds functionality to an existing service)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation or code sample

## Additional information

- This PR fixes or closes issue: fixes #285

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README

2020-09-25 11:54 UTC, Quentame requested changes
You should fix the CI before we merge

2020-09-25 11:54 UTC, Quentame commented on pyicloud/services/photos.py
> +                if "albumNameEnc" not in folder['fields']:
```suggestion
                if "albumNameEnc" not in folder["fields"]:
```

To fix Black formating

2020-09-25 12:00 UTC, merged

2022-04-19 06:40 UTC, fishmanxp commented
I have the same problem, and I don't know how to fix it, can you help me to fix it?
usa635241@163.com
![image](https://user-images.githubusercontent.com/15833327/163941575-bf22d78f-8214-43b2-af16-6d1d052f2b1e.png)

2022-04-26 05:51 UTC, fishmanxp commented
anyone can help me???